services:
    custom-rpi-image:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: rpi-web-kiosk:latest
        volumes:
            - ./custom-rpi-image:/home/imagegen/custom-rpi-image
            - ./app:/home/imagegen/app
            # don't mount nodes_modules and build folders
            - /home/imagegen/app/node_modules
            - /home/imagegen/app/build
    wifi_setup_service:
        build:
            context: ./wifi_setup_service
            dockerfile: Dockerfile.wifi_setup_service
        privileged: true
        stdin_open: true
        tty: true
        image: wifi_setup_service:latest
        volumes:
            - ./wifi_setup_service:/app