#!/bin/sh

set -eu

# Write out our systemd service to unblock wifi
rsync ../kiosk-conf/unblock-wifi.service $1/etc/systemd/system/unblock-wifi.service

mkdir -p $1/etc/wpa_supplicant

# Write out our systemd service to start our wifi setup service
cat ../kiosk-conf/wifi-setup.service.tpl | sed \
   -e "s|<KIOSK_HOMEPAGE_URL>|$IGconf_kiosk_homepage_url|g" \
   > $1/etc/systemd/system/wifi-setup.service

# # Enable the wifi-setup service so it starts automatically
$BDEBSTRAP_HOOKS/enable-units "$1" wifi-setup

# We'll run chromium like this
APP="/usr/bin/chromium-browser http://localhost:8080 \
   --kiosk --noerrdialogs --disable-infobars --disable-cursor \
   --no-first-run --ozone-platform=wayland \
   --enable-features=OverlayScrollbar --start-maximized"
# 
# Write out our systemd kiosk service
cat ../kiosk-conf/kiosk.service.tpl | sed \
   -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
   -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
   -e "s|<KIOSK_APP>|$APP|g" \
   > $1/etc/systemd/system/kiosk.service

# # Enable the kiosk service so it starts automatically
$BDEBSTRAP_HOOKS/enable-units "$1" kiosk